// Legacy mock data (not used — app fetches from Supabase via queries.ts)
// eslint-disable-next-line @typescript-eslint/no-unused-vars
export const opportunities = [
  {
    id: '1',
    title: 'Avenue Scholars Career Pathway',
    organization: 'Avenue Scholars Foundation',
    description:
      'A free program that connects low-income Omaha high school juniors and seniors with career coaches, paid internships, and post-secondary planning. Students get one-on-one mentoring and real work experience.',
    type: 'college_access',
    eligibility: 'Must be an 11th or 12th grader at a participating Omaha high school and qualify as low-income.',
    deadline: null,
    link: 'https://avenuescholars.org',
    location: 'Omaha',
    identity_tags: ['low_income', 'first_gen'],
    category_tags: ['leadership', 'business'],
    grade_levels: ['11', '12'],
    is_active: true,
    date_added: '2025-01-15',
    last_verified: '2025-09-01',
  },
  {
    id: '2',
    title: 'Susan Thompson Buffett Scholarship',
    organization: 'Susan Thompson Buffett Foundation',
    description:
      'Full-tuition scholarship for Nebraska residents attending a Nebraska public college or university. Covers tuition, fees, and provides a book stipend. One of the most generous state scholarships in the country.',
    type: 'scholarship',
    eligibility:
      'Must be a Nebraska resident, Pell Grant eligible, and attending a Nebraska public institution. Strong academic record preferred.',
    deadline: '2026-02-01',
    link: 'https://buffettscholarships.org',
    location: 'National',
    identity_tags: ['low_income', 'first_gen'],
    category_tags: [],
    grade_levels: ['12', 'college_freshman'],
    is_active: true,
    date_added: '2025-01-10',
    last_verified: '2025-09-15',
  },
  {
    id: '3',
    title: 'TRIO Upward Bound — UNO',
    organization: 'University of Nebraska at Omaha',
    description:
      'A federally funded program that helps first-generation and low-income high school students prepare for college. Includes tutoring, SAT/ACT prep, campus visits, and a summer residential program at UNO.',
    type: 'college_access',
    eligibility:
      'Must be a first-generation college student and/or from a low-income family. Must attend a target high school in the Omaha area.',
    deadline: '2026-03-15',
    link: 'https://www.unomaha.edu/student-life/inclusion/trio/upward-bound.php',
    location: 'Omaha',
    identity_tags: ['low_income', 'first_gen'],
    category_tags: ['stem', 'leadership'],
    grade_levels: ['9', '10', '11', '12'],
    is_active: true,
    date_added: '2025-01-20',
    last_verified: '2025-08-20',
  },
  {
    id: '4',
    title: 'Girls Inc. Eureka! STEM Program',
    organization: 'Girls Inc. of Omaha',
    description:
      'A free five-year STEM program for girls starting in 8th grade. Includes hands-on science experiments, college visits, internship placement, and mentoring from women in STEM careers.',
    type: 'summer_program',
    eligibility: 'Girls entering 8th grade in the Omaha metro area.',
    deadline: '2026-04-01',
    link: 'https://www.girlsincomaha.org',
    location: 'Omaha',
    identity_tags: ['women_stem', 'low_income'],
    category_tags: ['stem'],
    grade_levels: ['9', '10', '11', '12'],
    is_active: true,
    date_added: '2025-02-01',
    last_verified: '2025-09-10',
  },
  {
    id: '5',
    title: 'Hispanic Scholarship Fund',
    organization: 'Hispanic Scholarship Fund',
    description:
      'Scholarships ranging from $500 to $5,000 for Hispanic/Latino students who plan to enroll full-time in a four-year university. Based on academic achievement, financial need, and community involvement.',
    type: 'scholarship',
    eligibility:
      'Must be of Hispanic heritage, U.S. citizen or permanent resident, and have a minimum 3.0 GPA.',
    deadline: '2026-02-15',
    link: 'https://www.hsf.net/scholarship',
    location: 'National',
    identity_tags: ['hispanic'],
    category_tags: [],
    grade_levels: ['12', 'college_freshman'],
    is_active: true,
    date_added: '2025-01-25',
    last_verified: '2025-09-05',
  },
  {
    id: '6',
    title: 'Boys & Girls Club of the Midlands — Youth of the Year',
    organization: 'Boys & Girls Club of the Midlands',
    description:
      'Leadership program recognizing outstanding teens who demonstrate academic excellence, healthy lifestyles, and community service. Winners receive scholarship funds and advance to state/national competitions.',
    type: 'competition',
    eligibility:
      'Must be an active member of the Boys & Girls Club of the Midlands, ages 14-18.',
    deadline: '2026-01-31',
    link: 'https://www.bgcomaha.org',
    location: 'Omaha',
    identity_tags: ['low_income'],
    category_tags: ['leadership', 'community_service'],
    grade_levels: ['9', '10', '11', '12'],
    is_active: true,
    date_added: '2025-02-05',
    last_verified: '2025-08-30',
  },
  {
    id: '7',
    title: 'QuestBridge National College Match',
    organization: 'QuestBridge',
    description:
      'Matches high-achieving, low-income students with full four-year scholarships to top colleges including Yale, Stanford, MIT, and more. Selected students are guaranteed full financial aid.',
    type: 'scholarship',
    eligibility:
      'High school seniors from low-income backgrounds with strong academics. Household income typically under $65,000.',
    deadline: '2026-09-26',
    link: 'https://www.questbridge.org',
    location: 'National',
    identity_tags: ['low_income', 'first_gen'],
    category_tags: [],
    grade_levels: ['12'],
    is_active: true,
    date_added: '2025-03-01',
    last_verified: '2025-09-20',
  },
  {
    id: '8',
    title: 'Omaha Public Library — Free SAT/ACT Prep',
    organization: 'Omaha Public Library',
    description:
      'Free access to Peterson\'s Test Prep and other SAT/ACT study materials through your Omaha library card. Includes practice tests, study guides, and video tutorials — all completely free.',
    type: 'free_resource',
    eligibility: 'Anyone with an Omaha Public Library card.',
    deadline: null,
    link: 'https://omahalibrary.org',
    location: 'Omaha',
    identity_tags: [],
    category_tags: ['stem'],
    grade_levels: ['9', '10', '11', '12'],
    is_active: true,
    date_added: '2025-02-10',
    last_verified: '2025-09-01',
  },
  {
    id: '9',
    title: 'LULAC National Scholarship Fund',
    organization: 'League of United Latin American Citizens',
    description:
      'Scholarships for Hispanic/Latino students demonstrating academic achievement, community service, and leadership. Awards range from $250 to $2,000.',
    type: 'scholarship',
    eligibility:
      'Must be Hispanic/Latino, a U.S. citizen or permanent resident, and enrolled or planning to enroll in an accredited college.',
    deadline: '2026-03-31',
    link: 'https://lnesc.org/scholarships',
    location: 'National',
    identity_tags: ['hispanic'],
    category_tags: ['leadership'],
    grade_levels: ['12', 'college_freshman'],
    is_active: true,
    date_added: '2025-02-15',
    last_verified: '2025-09-10',
  },
  {
    id: '10',
    title: 'Ron Brown Scholar Program',
    organization: 'CAP Charitable Foundation',
    description:
      'Prestigious $40,000 scholarship ($10,000/year) for African American high school seniors who demonstrate academic excellence, leadership, and community service.',
    type: 'scholarship',
    eligibility:
      'Must be African American, a U.S. citizen or permanent resident, and a current high school senior with financial need.',
    deadline: '2026-01-09',
    link: 'https://www.ronbrown.org',
    location: 'National',
    identity_tags: ['black'],
    category_tags: ['leadership', 'community_service'],
    grade_levels: ['12'],
    is_active: true,
    date_added: '2025-02-20',
    last_verified: '2025-09-15',
  },
  {
    id: '11',
    title: 'Nebraska FAFSA Completion Workshop',
    organization: 'EducationQuest Foundation',
    description:
      'Free workshops across Nebraska to help students and families complete the FAFSA. Available in English and Spanish. Walk-ins welcome — bring your tax returns and FSA ID.',
    type: 'workshop',
    eligibility: 'Any student or family in Nebraska needing FAFSA help.',
    deadline: null,
    link: 'https://www.educationquest.org',
    location: 'Omaha',
    identity_tags: ['low_income', 'first_gen', 'esl'],
    category_tags: [],
    grade_levels: ['12', 'college_freshman'],
    is_active: true,
    date_added: '2025-03-01',
    last_verified: '2025-09-20',
  },
  {
    id: '12',
    title: 'Project Everlast — Foster Youth Support',
    organization: 'Project Everlast',
    description:
      'Connects current and former foster youth (ages 14-26) in Nebraska with resources including housing assistance, educational support, employment help, and a community of peers who understand.',
    type: 'mentorship',
    eligibility:
      'Current or former foster youth in Nebraska, ages 14-26.',
    deadline: null,
    link: 'https://www.projecteverlast.org',
    location: 'Omaha',
    identity_tags: ['foster_youth', 'low_income'],
    category_tags: ['leadership'],
    grade_levels: ['9', '10', '11', '12', 'college_freshman'],
    is_active: true,
    date_added: '2025-03-05',
    last_verified: '2025-09-01',
  },
  {
    id: '13',
    title: 'Gates Scholarship',
    organization: 'Bill & Melinda Gates Foundation',
    description:
      'A highly selective, full-cost scholarship for outstanding minority high school seniors from low-income households. Covers the full cost of attendance not already covered by financial aid.',
    type: 'scholarship',
    eligibility:
      'Must be a Pell-eligible minority student, U.S. citizen, and high school senior with a minimum 3.3 GPA.',
    deadline: '2026-09-15',
    link: 'https://www.thegatesscholarship.org',
    location: 'National',
    identity_tags: ['low_income', 'black', 'hispanic', 'native_american', 'asian_pacific'],
    category_tags: ['leadership'],
    grade_levels: ['12'],
    is_active: true,
    date_added: '2025-03-10',
    last_verified: '2025-09-20',
  },
  {
    id: '14',
    title: 'Heartland Workers Center — Youth Leadership',
    organization: 'Heartland Workers Center',
    description:
      'Leadership development program for immigrant and refugee youth in the Omaha area. Builds organizing skills, civic engagement, and community advocacy. Meets weekly with summer intensives.',
    type: 'mentorship',
    eligibility:
      'Immigrant or refugee youth in the Omaha metro area, ages 14-19.',
    deadline: null,
    link: 'https://www.heartlandworkerscenter.org',
    location: 'Omaha',
    identity_tags: ['immigrant', 'hispanic', 'esl'],
    category_tags: ['leadership', 'community_service'],
    grade_levels: ['9', '10', '11', '12'],
    is_active: true,
    date_added: '2025-03-15',
    last_verified: '2025-09-05',
  },
  {
    id: '15',
    title: 'Nebraska Indian Community College Summer Bridge',
    organization: 'Nebraska Indian Community College',
    description:
      'Summer bridge program helping Native American students transition from high school to college. Includes academic prep, cultural programming, and campus life orientation.',
    type: 'summer_program',
    eligibility:
      'Native American high school students in Nebraska planning to attend college.',
    deadline: '2026-05-01',
    link: 'https://www.thenicc.edu',
    location: 'Omaha',
    identity_tags: ['native_american', 'first_gen'],
    category_tags: ['leadership'],
    grade_levels: ['12'],
    is_active: true,
    date_added: '2025-03-20',
    last_verified: '2025-09-10',
  },
  {
    id: '16',
    title: 'Microsoft TEALS — AP Computer Science',
    organization: 'Microsoft Philanthropies',
    description:
      'Brings AP Computer Science to high schools that don\'t currently offer it. Volunteer tech professionals co-teach with your teacher. Completely free for students and schools.',
    type: 'free_resource',
    eligibility:
      'Students at participating high schools. Check if your school is part of the TEALS program.',
    deadline: null,
    link: 'https://www.microsoft.com/en-us/teals',
    location: 'National',
    identity_tags: ['low_income', 'rural'],
    category_tags: ['stem'],
    grade_levels: ['10', '11', '12'],
    is_active: true,
    date_added: '2025-04-01',
    last_verified: '2025-09-15',
  },
  {
    id: '17',
    title: 'Omaha Trades Academy — Pre-Apprenticeship',
    organization: 'Omaha Trades Academy',
    description:
      'Free pre-apprenticeship program introducing high school students to skilled trades: electrical, plumbing, HVAC, and construction. Includes hands-on training and job placement support.',
    type: 'internship',
    eligibility:
      'Omaha-area high school juniors and seniors interested in the trades.',
    deadline: '2026-03-01',
    link: 'https://www.omahatradesacademy.org',
    location: 'Omaha',
    identity_tags: ['low_income'],
    category_tags: ['trades'],
    grade_levels: ['11', '12'],
    is_active: true,
    date_added: '2025-04-05',
    last_verified: '2025-09-01',
  },
  {
    id: '18',
    title: 'Point Foundation LGBTQ Scholarship',
    organization: 'Point Foundation',
    description:
      'Scholarships, mentorship, and leadership training for LGBTQ+ students with strong academic records and demonstrated leadership. Awards vary based on financial need.',
    type: 'scholarship',
    eligibility:
      'LGBTQ+ identifying students enrolled or planning to enroll in a U.S. college or university.',
    deadline: '2026-01-28',
    link: 'https://pointfoundation.org',
    location: 'National',
    identity_tags: ['lgbtq'],
    category_tags: ['leadership'],
    grade_levels: ['12', 'college_freshman'],
    is_active: true,
    date_added: '2025-04-10',
    last_verified: '2025-09-20',
  },
]
