-- ============================================================
-- Opportography — Migration 036
-- Phase 12: Networking & Community Connection
-- Research: March 12, 2026
--
-- 16 verified networking organizations, professional
-- associations, maker spaces, and community groups serving
-- the Omaha / Council Bluffs metro.
--
-- All organizations verified active as of March 2026 via
-- official websites, Meetup pages, and social media.
-- ============================================================

INSERT INTO public.opportunities (
  title, organization, organization_website,
  description, type, networking_subcategory,
  eligibility, link,
  location, city, state, is_remote, is_hybrid,
  identity_tags, category_tags,
  compensation_type,
  schedule,
  data_confidence, verification_status,
  source_url, source_type, source_retrieved_date,
  who_shows_up, networking_value,
  is_active, is_featured
) VALUES

-- ── 1. 1 Million Cups Omaha ─────────────────────────────────────────────────
(
  '1 Million Cups Omaha',
  '1MC Omaha',
  'https://www.1millioncups.com/omaha',
  '1 Million Cups (1MC) is a national program by the Ewing Marion Kauffman Foundation that connects entrepreneurs with the community over coffee. Every Wednesday morning, two local startups or early-stage ventures present their businesses to a room of founders, mentors, investors, and community members. Attendance is completely free, no RSVP required. Presentations are followed by open Q&A and structured feedback. Held at Millwork Commons (1229 Millwork Ave) — Omaha''s startup district. This is one of the best low-barrier entry points into the Omaha entrepreneurship community for anyone with a business idea or who wants to meet founders.',
  'networking',
  'startup_entrepreneurship',
  'Open to anyone. No application, no cost. Show up Wednesday morning. Great for aspiring entrepreneurs, current founders at any stage, investors, mentors, or anyone curious about the local startup ecosystem.',
  'https://www.1millioncups.com/omaha',
  'Omaha, NE',
  'Omaha', 'NE', false, false,
  array[]::text[],
  array['business', 'leadership'],
  'unpaid',
  'Every Wednesday, 8:30–9:30 AM at Millwork Commons (1229 Millwork Ave, Omaha)',
  'high',
  'verified',
  'https://www.1millioncups.com/omaha',
  'official_website',
  '2026-03-12',
  '{"typical_attendees": "Founders, entrepreneurs, startup employees, investors, mentors, university students, career changers", "experience_level": "All levels — many attendees are exploring entrepreneurship for the first time", "age_range": "18+", "notes": "Very welcoming to first-timers. Coffee and community, no pressure."}',
  '{"primary_value": "See how startups pitch and get feedback. Meet Omaha''s entrepreneurial community in one hour a week.", "for_newcomers": "No registration needed — just show up. Excellent entry point to Omaha startup culture.", "for_job_seekers": "Early-stage companies often hire through this network. Direct founder access.", "notes": "Free. Kauffman Foundation program active in 180+ cities."}',
  true, true
),

-- ── 2. MYLPA — Metro Young Latino Professionals Association ──────────────────
(
  'Metro Young Latino Professionals Association (MYLPA)',
  'MYLPA',
  'https://www.mylpaomaha.com',
  'MYLPA is Omaha''s professional network for Latino young adults and their allies — open to all who support the mission. The organization hosts regular networking events, leadership development programs (including Board Masters Training for those interested in nonprofit board service), and community gatherings. MYLPA is a 501(c)(3) nonprofit connecting Latino professionals across industries with mentors, peers, and career opportunities. They partner with major Omaha employers and civic organizations, providing access that is otherwise difficult to find.',
  'networking',
  'identity_based',
  'Open to all. Primarily serves Latino young professionals, but explicitly welcoming to allies and non-Latino members. Typical age range is 21–40, but no strict restriction.',
  'https://www.mylpaomaha.com',
  'Omaha, NE',
  'Omaha', 'NE', false, false,
  array['hispanic']::text[],
  array['business', 'leadership', 'community_service'],
  'unpaid',
  'Regular events throughout the year — check website and social media for schedule',
  'high',
  'verified',
  'https://www.mylpaomaha.com',
  'official_website',
  '2026-03-12',
  '{"typical_attendees": "Latino professionals in business, healthcare, education, government, and non-profits. Allies and non-Latino members welcome.", "experience_level": "Entry-level through mid-career", "age_range": "21–40 typical", "notes": "One of the most active identity-based professional networks in Omaha."}',
  '{"primary_value": "Latino professional network — mentors, peers, employers, civic leaders", "for_newcomers": "Welcoming to new grads and first-time professionals. Board Masters Training prepares members for nonprofit board service.", "for_job_seekers": "Direct connections to Latino-friendly employers who partner with MYLPA.", "notes": "501(c)(3) — volunteer leadership opportunities available."}',
  true, true
),

-- ── 3. Midlands African Chamber of Commerce ──────────────────────────────────
(
  'Midlands African Chamber of Commerce — Weekly Events',
  'Midlands African Chamber of Commerce',
  'https://midlandsafricanchamber.com',
  'The Midlands African Chamber of Commerce is one of the most active business development organizations for African and African American entrepreneurs in the Omaha metro. They run daily programming: Xcelerate Mondays (business acceleration), Roll Call Wednesdays (accountability), Power Up Thursdays (skill-building), and Pitch Black Fridays (pitch practice and investor networking). Annual flagship event: Pitch Black Conference — a major entrepreneurship and pitch competition offering $15,000 prize money and $40,000 in in-kind support. The 2026 Pitch Black Conference is scheduled for May 2, 2026. Attending weekly events is free.',
  'networking',
  'identity_based',
  'Open to all. Primarily serves African and African American business owners and entrepreneurs, but all are welcome. Pitch Black Conference open to entrepreneurs of all backgrounds.',
  'https://midlandsafricanchamber.com',
  'Omaha, NE',
  'Omaha', 'NE', false, false,
  array['black']::text[],
  array['business', 'leadership'],
  'unpaid',
  'Weekly: Xcelerate Mondays, Roll Call Wednesdays, Power Up Thursdays, Pitch Black Fridays. Pitch Black Conference: May 2, 2026',
  'high',
  'verified',
  'https://midlandsafricanchamber.com',
  'official_website',
  '2026-03-12',
  '{"typical_attendees": "African and African American business owners, entrepreneurs, aspiring founders, investors, community leaders", "experience_level": "All levels", "age_range": "18+", "notes": "Very active community with daily programming. Pitch Black Conference is a marquee regional event."}',
  '{"primary_value": "Business development, funding access, peer accountability, investor connections for Black entrepreneurs", "for_newcomers": "Daily events mean you can drop in any week. Low-barrier and welcoming.", "for_job_seekers": "Network includes many business owners who hire locally. Strong community ties.", "notes": "Pitch Black Conference: $15,000 prize + $40k in-kind. wepitchblack.com for conference registration."}',
  true, true
),

-- ── 4. Empowerment Network / African American Professional Network ────────────
(
  'Empowerment Network — African American Professional Network (AAPN)',
  'Empowerment Network',
  'https://empoweromaha.com',
  'The Empowerment Network is a cornerstone institution in North and South Omaha''s African American community, focused on economic empowerment, workforce development, and neighborhood revitalization. Their African American Professional Network (AAPN) connects Black professionals across industries for career networking, mentorship, and community investment. Annual events include the Revive Black Business Summit (held January 2026, confirmed active). The Empowerment Network partners with major employers and civic institutions across the metro. Rooted in the 24th & Lake St. historic district.',
  'networking',
  'identity_based',
  'Open to all. Primarily serves African American professionals, community leaders, and residents of North and South Omaha. All community members welcome.',
  'https://empoweromaha.com',
  'Omaha, NE',
  'Omaha', 'NE', false, false,
  array['black']::text[],
  array['business', 'leadership', 'community_service'],
  'unpaid',
  'Regular events and programming throughout the year — check empoweromaha.com for schedule',
  'high',
  'verified',
  'https://empoweromaha.com',
  'official_website',
  '2026-03-12',
  '{"typical_attendees": "African American professionals, community leaders, business owners, workforce development participants, civic advocates", "experience_level": "All levels", "age_range": "18+", "notes": "Deep roots in North and South Omaha. Revive Black Business Summit is a major annual event."}',
  '{"primary_value": "Professional network, community investment, workforce development, and Black business support in Omaha", "for_newcomers": "Strong community orientation — good for people new to Omaha or new to professional networking.", "for_job_seekers": "Employer partnerships and workforce development programs.", "notes": "One of Omaha''s most established African American community institutions."}',
  true, false
),

-- ── 5. 100 Black Men of Omaha ────────────────────────────────────────────────
(
  '100 Black Men of Omaha',
  '100 Black Men of Omaha, Inc.',
  'https://100blackmenomaha.org',
  '100 Black Men of Omaha is an affiliate chapter of 100 Black Men of America — a national mentorship and leadership organization with 100+ chapters. Since 1995, the Omaha chapter has served Black youth and young adults through mentorship, education, health and wellness, and economic empowerment programs. During the 2024–25 program year, they impacted 1,040 youth across the metro. In addition to youth mentorship, the organization is a professional network for Black men and their allies — members are business professionals, community leaders, and mentors. Their 19th Annual African-American History Challenge is a signature community event.',
  'networking',
  'identity_based',
  'Youth programs: open to Black youth and young men in the Omaha metro. Membership as a professional member open to men committed to the mission. Events open to community.',
  'https://100blackmenomaha.org',
  'Omaha, NE (2221 N. 24th St)',
  'Omaha', 'NE', false, false,
  array['black']::text[],
  array['leadership', 'community_service'],
  'unpaid',
  'Year-round programming and events — check 100blackmenomaha.org for schedule',
  'high',
  'verified',
  'https://100blackmenomaha.org',
  'official_website',
  '2026-03-12',
  '{"typical_attendees": "Black male professionals, community leaders, mentors, youth program participants, allies", "experience_level": "All levels — strong mentorship component for young adults", "age_range": "Youth programs: middle/high school. Professional membership: 18+", "notes": "National organization with strong Omaha chapter. 1,040 youth served in 2024–25."}',
  '{"primary_value": "Mentorship, professional network, community leadership for Black men and youth in Omaha", "for_newcomers": "Clear pathways to get involved as a volunteer mentor or program participant.", "for_job_seekers": "Member network includes employers and community leaders.", "notes": "501(c)(3). National chapter affiliation opens doors beyond Omaha."}',
  true, false
),

-- ── 6. HRAM — Human Resource Association of the Midlands (SHRM) ─────────────
(
  'Human Resource Association of the Midlands (HRAM/SHRM)',
  'Human Resource Association of the Midlands',
  'https://www.hram.org',
  'HRAM is the premier HR professional organization in the Omaha/Council Bluffs metro — and one of the largest SHRM-affiliated chapters in the country (classified as a "super-mega" chapter with 1,000+ members). Monthly programming covers HR law, talent acquisition, DEI, compensation, benefits, and leadership. Events include the monthly Chapter Program (2nd Tuesday, 7:30–9:30 AM), First Fridays Membership Social, HR Breakfast Buzz, and HR Brew Crew social. HRAM is essential for anyone pursuing HR as a career — it is where Omaha''s hiring managers and talent acquisition leaders network. Student membership is available at a reduced rate.',
  'networking',
  'professional_assoc',
  'Open to HR professionals at all levels, students studying HR or business, and people transitioning into HR careers. Student membership available. Individual membership is paid (check hram.org for rates).',
  'https://www.hram.org',
  'Omaha, NE',
  'Omaha', 'NE', false, false,
  array[]::text[],
  array['business', 'leadership'],
  'unpaid',
  'Monthly Chapter Program (2nd Tuesday, 7:30–9:30 AM), First Fridays Social, HR Breakfast Buzz, HR Brew Crew social — see hram.org/events for full calendar',
  'high',
  'verified',
  'https://www.hram.org',
  'official_website',
  '2026-03-12',
  '{"typical_attendees": "HR professionals, recruiters, talent acquisition specialists, HR managers and directors, SHRM certification holders, HR students", "experience_level": "Entry through C-suite", "age_range": "22+", "notes": "1,000+ members. Membership is paid but student rates are reduced. The room is full of people who make hiring decisions."}',
  '{"primary_value": "HR career development, professional certification support (SHRM-CP/SCP), direct access to Omaha hiring leaders", "for_newcomers": "Monthly events have dedicated networking time. First Fridays social is informal and welcoming.", "for_job_seekers": "This is where Omaha recruiters and HR managers gather. High-value for anyone in or entering HR.", "notes": "SHRM certification study groups often organized through HRAM."}',
  true, false
),

-- ── 7. PMI Heartland Chapter ─────────────────────────────────────────────────
(
  'PMI Heartland Chapter — Project Management Professionals',
  'PMI Heartland Chapter',
  'https://pmiheartland.org',
  'PMI Heartland is the Omaha/Council Bluffs metro chapter of the Project Management Institute — the global standard for project management credentials (PMP, CAPM, PMI-ACP). Monthly luncheon meetings are held on the third Wednesday of each month (11 AM–1 PM) at Scott Conference Center (6450 Pine St, Omaha). Established in 1993, the chapter serves project managers, program managers, business analysts, and Agile practitioners across eastern Nebraska and western Iowa. PDUs (Professional Development Units) for PMP maintenance are earned at chapter events. Free for guests — membership is paid.',
  'networking',
  'professional_assoc',
  'Open to project managers, program managers, business analysts, Agile practitioners, and anyone working toward PMI certification. Guests may attend events for free before deciding to join. Membership fee applies for full access.',
  'https://pmiheartland.org',
  'Omaha, NE',
  'Omaha', 'NE', false, false,
  array[]::text[],
  array['business', 'leadership'],
  'unpaid',
  'Monthly luncheon: 3rd Wednesday of each month, 11 AM–1 PM, Scott Conference Center (6450 Pine St, Omaha)',
  'high',
  'verified',
  'https://pmiheartland.org',
  'official_website',
  '2026-03-12',
  '{"typical_attendees": "Project managers, program managers, business analysts, Agile practitioners, IT managers, construction project managers, healthcare operations staff", "experience_level": "Entry through senior/director", "age_range": "25+", "notes": "Monthly luncheon at Scott Conference Center — professional environment, regular networking built in."}',
  '{"primary_value": "PMP/CAPM certification support, PDU credits, project management career network across industries", "for_newcomers": "Guests attend for free. Chapter is established (since 1993) and welcoming to newcomers.", "for_job_seekers": "Strong network across construction, healthcare, tech, insurance, and government sectors in Omaha.", "notes": "PMI certifications are highly valued in Omaha''s corporate and construction sectors."}',
  true, false
),

-- ── 8. AIGA Nebraska — Design Professionals ──────────────────────────────────
(
  'AIGA Nebraska — Design Professionals Network',
  'AIGA Nebraska',
  'https://nebraska.aiga.org',
  'AIGA Nebraska is the Omaha chapter of the American Institute of Graphic Arts — the nation''s oldest and largest professional membership organization for designers. The chapter serves graphic designers, UX/UI designers, art directors, brand strategists, illustrators, and design educators across Nebraska. Events include portfolio reviews, design critiques, speaker series, and social mixers. AIGA Nebraska provides a community for working designers and students entering the profession. Attending events is low-cost or free for non-members; full membership unlocks AIGA national resources.',
  'networking',
  'professional_assoc',
  'Open to designers at all levels — graphic design, UX/UI, brand, illustration, motion, typography. Students and recent grads especially welcome. Non-members can attend events.',
  'https://nebraska.aiga.org',
  'Omaha, NE',
  'Omaha', 'NE', false, false,
  array[]::text[],
  array['arts', 'business'],
  'unpaid',
  'Regular events throughout the year — see nebraska.aiga.org/events for schedule',
  'high',
  'verified',
  'https://nebraska.aiga.org',
  'official_website',
  '2026-03-12',
  '{"typical_attendees": "Graphic designers, UX/UI designers, art directors, brand strategists, design students, illustrators, design educators at Creighton/UNO/MCC", "experience_level": "Students through senior professionals", "age_range": "18+", "notes": "Portfolio reviews are especially valuable for students and new grads."}',
  '{"primary_value": "Design community, portfolio feedback, creative career network, and professional development for Omaha designers", "for_newcomers": "Portfolio reviews and critiques help recent grads improve work before job searching.", "for_job_seekers": "Design agencies and in-house creative teams recruit through AIGA community connections.", "notes": "AIGA national membership includes mentorship tools and job board access."}',
  true, false
),

-- ── 9. Heartland Women's Network (HWN) ───────────────────────────────────────
(
  'Heartland Women''s Network (HWN) — Monthly Luncheons',
  'Heartland Women''s Network',
  'https://www.heartlandwomensnetwork.com',
  'Heartland Women''s Network (HWN) is one of Omaha''s longest-running women''s professional networks. Monthly luncheon events bring together women from business, healthcare, education, nonprofit, and entrepreneurship for networking and a featured speaker. HWN members come from "all walks of life" — business professionals, business owners, primary caregivers, and college students. The March 2026 luncheon features a speaker on March 18. HWN''s 2026 Non-Profit Partner is Heartland Equine Therapeutic Riding Academy (HETRA), and members collect donation items at meetings. Membership is paid; guests may attend.',
  'networking',
  'identity_based',
  'Open to women professionals, business owners, students, and career changers. Guests may attend before joining. Membership is paid (see heartlandwomensnetwork.com for rates). Contact: (402) 778-7960.',
  'https://www.heartlandwomensnetwork.com',
  'Omaha, NE',
  'Omaha', 'NE', false, false,
  array[]::text[],
  array['business', 'leadership', 'community_service'],
  'unpaid',
  'Monthly luncheon — typically the 3rd Wednesday. March 2026: March 18. Check heartlandwomensnetwork.com/calendar for current schedule.',
  'high',
  'verified',
  'https://www.heartlandwomensnetwork.com',
  'official_website',
  '2026-03-12',
  '{"typical_attendees": "Women business owners, corporate professionals, nonprofit leaders, healthcare workers, educators, college students, primary caregivers", "experience_level": "All levels", "age_range": "18+", "notes": "Long-standing Omaha women''s network — welcoming to newcomers at any career stage."}',
  '{"primary_value": "Women''s professional network across industries — speaker insights, peer connections, community service", "for_newcomers": "Monthly format is accessible. Guest attendance is welcome before committing to membership.", "for_job_seekers": "Diverse membership spans many industries and includes hiring managers.", "notes": "One of Omaha''s longest-running women''s professional organizations."}',
  true, false
),

-- ── 10. Council Bluffs Young Professionals (CBYP) ────────────────────────────
(
  'Council Bluffs Young Professionals (CBYP)',
  'Council Bluffs Area Chamber of Commerce',
  'https://www.councilbluffsiowa.com/council-bluffs-young-professionals/',
  'Council Bluffs Young Professionals (CBYP) is a network for young adults ages 18–40 focused on career growth, leadership development, and community engagement in the Council Bluffs area. Hosted by the Council Bluffs Area Chamber of Commerce, CBYP hosts networking events, workshops, and community gatherings designed to help young professionals build connections, develop leadership skills, and invest in the CB community. This is the primary young professional network for residents of Council Bluffs who want to build their career and community presence locally rather than commuting to Omaha for networking.',
  'networking',
  'young_professionals',
  'Open to adults ages 18–40 in Council Bluffs and the surrounding metro. No prior membership or professional experience required. Chamber membership not required to participate in most events.',
  'https://www.councilbluffsiowa.com/council-bluffs-young-professionals/',
  'Council Bluffs, IA',
  'Council Bluffs', 'IA', false, false,
  array[]::text[],
  array['business', 'leadership', 'community_service'],
  'unpaid',
  'Regular events throughout the year — check councilbluffsiowa.com for schedule',
  'high',
  'verified',
  'https://www.councilbluffsiowa.com/council-bluffs-young-professionals/',
  'official_website',
  '2026-03-12',
  '{"typical_attendees": "Young professionals ages 18–40 living or working in Council Bluffs, across all industries", "experience_level": "Entry-level through mid-career", "age_range": "18–40", "notes": "Council Bluffs-focused — distinct from Omaha YP networks. Valuable for CB residents."}',
  '{"primary_value": "Build a professional and social network within Council Bluffs. Leadership development and community investment.", "for_newcomers": "Explicitly designed for young adults entering professional life. Low barrier to participation.", "for_job_seekers": "CB Chamber connections span healthcare, government, retail, and hospitality employers in CB.", "notes": "Ages 18–40. Council Bluffs Area Chamber of Commerce affiliation provides access to the broader business community."}',
  true, false
),

-- ── 11. NebraskaJS — JavaScript Developers ───────────────────────────────────
(
  'NebraskaJS — Monthly JavaScript Meetup',
  'NebraskaJS',
  'https://nebraskajs.com',
  'NebraskaJS is Omaha''s monthly JavaScript developer meetup — active since 2009 and one of the longest-running tech communities in the metro. Meetings feature two technical talks (talks on JavaScript, Node.js, React, TypeScript, web standards, tooling, and adjacent topics), followed by networking. The March 11, 2026 meetup was confirmed active. Meetings run 5:30–7:30 PM. Completely free to attend — no registration required. This is a core community for front-end developers, full-stack developers, and anyone working with JavaScript in Omaha.',
  'networking',
  'tech_community',
  'Open to anyone interested in JavaScript and web development — beginners to senior engineers welcome. No registration required. Speakers may submit talk proposals via nebraskajs.com.',
  'https://nebraskajs.com',
  'Omaha, NE',
  'Omaha', 'NE', false, false,
  array[]::text[],
  array['stem', 'business'],
  'unpaid',
  'Monthly — typically 2nd Tuesday, 5:30–7:30 PM. March 11, 2026 confirmed. Check nebraskajs.com for location and schedule.',
  'high',
  'verified',
  'https://nebraskajs.com',
  'official_website',
  '2026-03-12',
  '{"typical_attendees": "Front-end developers, full-stack developers, JavaScript engineers, bootcamp grads, CS students, UX engineers, tech job seekers", "experience_level": "All levels — talks often range from beginner to advanced", "age_range": "18+", "notes": "Active since 2009. One of Omaha''s oldest tech communities. Very welcoming to newcomers."}',
  '{"primary_value": "JavaScript/web development community, technical learning, peer network for Omaha developers", "for_newcomers": "Free, no registration. The networking segment after talks is accessible even for beginners.", "for_job_seekers": "Many attendees work at or recruit for Omaha tech companies. Great for referrals.", "notes": "Free. Speaker proposals welcome. Core of Omaha''s front-end developer community."}',
  true, true
),

-- ── 12. Beer && Code Omaha ────────────────────────────────────────────────────
(
  'Beer && Code Omaha — Monthly Developer Social',
  'Beer && Code',
  'https://www.beerandcode.org',
  'Beer && Code is a monthly informal gathering for programmers and tech workers in Omaha — part social meetup, part co-working session at a local pub. Held on the third Thursday of each month at rotating Omaha bars, it''s intentionally casual: bring your laptop, work on a side project, talk to other developers, and enjoy a beverage. No presentations, no agenda. This is the social complement to structured meetups like NebraskaJS — it''s where Omaha developers decompress, connect across stacks (front-end, back-end, mobile, data), and build friendships within the tech community.',
  'networking',
  'tech_community',
  'Open to any programmer, developer, designer, data scientist, or tech worker. No skill level requirement — if you write code or want to, you belong here. Check beerandcode.org or follow on social for venue announcement each month.',
  'https://www.beerandcode.org',
  'Omaha, NE (rotating venues)',
  'Omaha', 'NE', false, false,
  array[]::text[],
  array['stem'],
  'unpaid',
  'Monthly — 3rd Thursday evening. Location announced before each event at beerandcode.org',
  'medium',
  'needs_confirmation',
  'https://www.beerandcode.org',
  'official_website',
  '2026-03-12',
  '{"typical_attendees": "Software developers, front-end engineers, back-end engineers, mobile developers, data engineers, tech designers, bootcamp grads", "experience_level": "All levels — very informal", "age_range": "21+ (bar venue)", "notes": "Rotating pub venues — must be 21+. Casual, no agenda."}',
  '{"primary_value": "Informal social networking for Omaha developers. Co-working atmosphere with community.", "for_newcomers": "No presentations or skill requirements. Low-pressure entry point to Omaha tech community.", "for_job_seekers": "Developers from many Omaha companies attend. Referral-friendly environment.", "notes": "Must be 21+ for bar venues. Verify current activity at beerandcode.org before going."}',
  true, false
),

-- ── 13. Omaha Maker Group (OMG) ───────────────────────────────────────────────
(
  'Omaha Maker Group — Tuesday Open Shop Nights',
  'Omaha Maker Group',
  'https://omahamakergroup.org',
  'Omaha Maker Group (OMG) is Omaha''s primary makerspace — a community workshop with laser cutters, 3D printers, electronics equipment, woodworking tools, and more. Tuesday Open Shop Nights are open to the public (members and guests) — drop in, see the space, work on projects, and meet other makers. Monthly membership is $40 for full access to equipment and the space 24/7. OMG is a cross-disciplinary community: software engineers, artists, engineers, hobbyists, and entrepreneurs all share the space. Great for hands-on learners, people who build things, and anyone exploring hardware, fabrication, or maker culture.',
  'networking',
  'maker_creative',
  'Open to all. Tuesday Open Shop Nights are free to visit as a guest. Monthly membership ($40/mo) provides 24/7 access and equipment use. No prior experience required for most equipment (training provided for safety-critical tools).',
  'https://omahamakergroup.org',
  'Omaha, NE',
  'Omaha', 'NE', false, false,
  array[]::text[],
  array['stem', 'arts'],
  'unpaid',
  'Tuesday Open Shop Nights — weekly. Full membership: $40/month for 24/7 access. Check omahamakergroup.org for current Tuesday hours.',
  'high',
  'verified',
  'https://omahamakergroup.org',
  'official_website',
  '2026-03-12',
  '{"typical_attendees": "Makers, hobbyists, software engineers building hardware projects, artists using fabrication, entrepreneurs prototyping products, students", "experience_level": "All levels — beginners welcome", "age_range": "All ages (minors with parent supervision)", "notes": "Cross-disciplinary community. 3D printing, laser cutting, electronics, woodworking, and more."}',
  '{"primary_value": "Access to fabrication equipment, maker community, hands-on project collaboration", "for_newcomers": "Tuesday Open Nights are the best first visit — free, casual, equipment demonstrations available.", "for_job_seekers": "Great for building a hardware/maker portfolio. Members span tech, engineering, and creative industries.", "notes": "$40/month membership. Tuesday nights are free to attend as a guest."}',
  true, false
),

-- ── 14. Do Space — Free Digital Skills & Community Tech ──────────────────────
(
  'Do Space — Free Digital Skills and Community Technology Center',
  'Do Space (Omaha Public Library)',
  'https://dospace.org',
  'Do Space is a free technology library and community learning center now operated by Omaha Public Library. It provides free access to computers, 3D printers, recording equipment, VR hardware, and maker tools — alongside free classes and workshops on digital skills, coding, design, and career readiness. Do Space is relocating to a new Central Library location in April 2026. No membership fee — completely free and open to the public. Do Space serves as an equalizer: anyone without home internet, a quality computer, or money for training can access professional-grade tools and learning at no cost.',
  'networking',
  'maker_creative',
  'Open to all ages, completely free. No registration required for general access. Some workshops require sign-up in advance. ID required for library card (opens full resource access).',
  'https://dospace.org',
  'Omaha, NE (new Central Library location, April 2026)',
  'Omaha', 'NE', false, false,
  array['low_income']::text[],
  array['stem', 'arts', 'business'],
  'unpaid',
  'Regular hours as part of Omaha Public Library — see dospace.org for current schedule and class calendar',
  'high',
  'verified',
  'https://dospace.org',
  'official_website',
  '2026-03-12',
  '{"typical_attendees": "Students, job seekers, entrepreneurs, community members of all ages and backgrounds, people without home internet or computer access, career changers", "experience_level": "All levels — explicitly designed for beginners", "age_range": "All ages", "notes": "Completely free. Moved to new Central Library location April 2026. Critical resource for digital equity."}',
  '{"primary_value": "Free access to computers, 3D printers, VR, recording equipment, and digital skills workshops", "for_newcomers": "Zero-barrier entry — just walk in. Staff available to help with equipment.", "for_job_seekers": "Free digital skills classes (coding, design, Microsoft Office, job search tools) directly applicable to employment.", "notes": "100% free. Omaha Public Library card opens full access. New location April 2026."}',
  true, true
),

-- ── 15. Sarpy County EmPower Breakfast ───────────────────────────────────────
(
  'Sarpy County EmPower Breakfast — Monthly Networking',
  'EmPower Breakfast',
  'https://www.empowerbreakfast.org',
  'EmPower Breakfast is a monthly early-morning networking breakfast in Papillion serving professionals from Sarpy County and the southern Omaha metro. Held on the third Tuesday of each month, it is specifically designed as a non-membership, non-commitment event — no dues, no required attendance. Simply show up for a structured networking breakfast. This model makes it one of the most accessible professional networking events in the metro for people who live in Bellevue, Papillion, La Vista, or Ralston. Attendees span all industries and career stages.',
  'networking',
  'civic_social',
  'Open to anyone. No membership required, no registration fees, no commitment. Just show up. Held at a restaurant in Papillion — check empowerbreakfast.org for current venue.',
  'https://www.empowerbreakfast.org',
  'Papillion, NE',
  'Papillion', 'NE', false, false,
  array[]::text[],
  array['business', 'leadership'],
  'unpaid',
  '3rd Tuesday of each month, morning. Check empowerbreakfast.org for venue and exact time.',
  'high',
  'verified',
  'https://www.empowerbreakfast.org',
  'official_website',
  '2026-03-12',
  '{"typical_attendees": "Professionals from Sarpy County (Papillion, Bellevue, La Vista, Ralston) across all industries — insurance, healthcare, construction, real estate, finance, small business", "experience_level": "All levels", "age_range": "22+", "notes": "Deliberately non-membership model. Very accessible for people who want networking without a subscription."}',
  '{"primary_value": "No-commitment monthly professional networking for Sarpy County / south metro professionals", "for_newcomers": "Zero barriers — no membership, no registration, no dues. Perfect for first-time networkers.", "for_job_seekers": "South metro-focused attendees include many small business owners and mid-sized employer representatives.", "notes": "Papillion location. No membership. Third Tuesday monthly."}',
  true, false
),

-- ── 16. Omaha Pedalers Bicycle Club ──────────────────────────────────────────
(
  'Omaha Pedalers Bicycle Club — Weekly Group Rides',
  'Omaha Pedalers Bicycle Club',
  'https://opbc.clubexpress.com',
  'Founded in 1969, Omaha Pedalers Bicycle Club (OPBC) is Omaha''s premier recreational cycling club — one of the most social, beginner-friendly clubs in the city. Weekly rides include Wednesday Evening Hump Day Ride (Greenstreet Cycles, 24th & Harney, 5:30 PM → Aksarben Village along the Keystone Trail), Thursday Rusty Spokes morning ride, and weekend group rides of varying distances and paces. Annual events include the Great American Pie Ride and the 36th Annual Corporate Cycling Challenge on August 16, 2026. Rides are open to the public. The club attracts people who want to build fitness, explore Omaha on a bike, and meet a genuinely friendly community.',
  'networking',
  'civic_social',
  'Open to all cyclists at any fitness level. Most group rides are welcoming to beginners — ride descriptions note pace so you can choose the right fit. A bike in working condition is all you need. Membership is voluntary ($20–$30/year for club benefits); rides are open to non-members.',
  'https://opbc.clubexpress.com',
  'Omaha, NE',
  'Omaha', 'NE', false, false,
  array[]::text[],
  array['athletics', 'community_service'],
  'unpaid',
  'Weekly: Wednesday Hump Day Ride (5:30 PM, Greenstreet Cycles, 24th & Harney), Thursday Rusty Spokes morning ride, weekend rides. Annual: Corporate Cycling Challenge Aug 16, 2026. Full calendar at opbc.clubexpress.com.',
  'high',
  'verified',
  'https://opbc.clubexpress.com',
  'official_website',
  '2026-03-12',
  '{"typical_attendees": "Recreational cyclists of all fitness levels, outdoor enthusiasts, people looking for active social community, commuter cyclists, families", "experience_level": "All fitness levels — rides are clearly rated by pace", "age_range": "All ages", "notes": "Founded 1969. One of Omaha''s oldest recreational clubs. Very welcoming. Membership optional."}',
  '{"primary_value": "Recreational cycling community — fitness, Omaha trail exploration, social connection outdoors", "for_newcomers": "Wednesday evening ride is an easy first experience — short, social, along the Keystone Trail.", "for_job_seekers": "Less career-focused, more community-focused. Excellent for building social capital and meeting people across industries.", "notes": "Annual Corporate Cycling Challenge August 16, 2026. Corporate teams and individuals welcome."}',
  true, false
);
